type = "V8"

INPUT_W = 640
INPUT_H = 640

NUM_KPTS = 8
NUM_CLASSES = 1
NUM_COLORS = 2
NUM_TSIZES = 1

BBOX_CONF_THRESH = 0.30
NMS_THRESH = 0.7
MERGE_THRESH = 0.8

model_prefix = "models/anti_wind/AWN802/AWN802"

# for drawing
point_num = 4
class_names = [""]
color_names = ["B", "R"]
tsize_names = ["", ""] # N/A
