type = "V5"

INPUT_W = 640
INPUT_H = 640

NUM_CLASSES = 3
NUM_COLORS = 4

BBOX_CONF_THRESH = 0.7
NMS_THRESH = 0.7
MERGE_THRESH = 0.8

anchors = [
    [4.0,5.0, 8.0,10.0, 13.0,16.0],
    [23.0,29.0, 43.0,55.0, 73.0,105.0],
    [146.0,217.0, 231.0,300.0, 335.0,433.0],
]

model_prefix = "models/wind/WN731/WN731_v5"

# for drawing
point_num = 5
class_names = ["C", "T", "U"]
color_names = ["B", "R", "N", "P"]
tsize_names = ["", ""] # N/A