type = "V8"

INPUT_W = 640
INPUT_H = 640

NUM_KPTS = 8
NUM_CLASSES = 8
NUM_COLORS = 4
NUM_TSIZES = 2

BBOX_CONF_THRESH = 0.60
NMS_THRESH = 0.7
MERGE_THRESH = 0.8

model_prefix = "models/v8/N514B/N514B"

# for drawing
point_num = 4
class_names = ["0", "1", "2", "3", "4", "5", "6", "7"]
color_names = ["B", "R", "N", "P"]
tsize_names = ["[S]", "[L]"]